# environment
env: XarmReach-v0
reward_type: sparse
use_her: True
GUI: False
seed: 0
max_reward: 1 # max reward to judge if done

# buffer
buffer_size: 1000
replay_k: 4

# network
hidden_sizes: [64, 64]

# train
actor_lr: 1.0e-3
critic_lr: 1.0e-3
start_timesteps: 100 # warmup
epoch: 1 # save times
step_per_epoch: 1000 # save interval (50repeat)
step_per_collect: 100 #(64path) after collect #, update
update_per_step: 0.02 # reuse time of steps
estimation_step: 1 # look ahead time steps
batch_size:  5

# parallel
device: cuda
training_num: 1
test_num: 1

# Algorithm
alpha: 0.2 # entropy regularization coefficient
auto_alpha: False
alpha_lr: 3e-4 # works if open auto alpha
tau: 0.005
gamma: 0.99

# dir
logdir: log
resume_path: null
save_render: False

# render
watch_train: False # if show demo directly
render: 0.00 # render time rate