# environment
info: Try to replace 1step-update with 20step-update
env: FetchReach-v1
dim: 2
reward_type: sparse
fail_reward: -50
seed: 5

# buffer
# buffer_size: 16000000
buffer_size: 1000000
replay_k: 4

# network
hidden_sizes: [64, 64]

# train
actor_lr: 1.0e-3
critic_lr: 1.0e-3
# start_timesteps: 160000 # warmup·
start_timesteps: 1000 # warmup
epoch: 100 # save times
step_per_epoch: 200 # save interval (50repeat)
step_per_collect: 20 #(64path) after collect #, update
update_per_step: 1 # repeat update time
estimation_step: 1 # look ahead time steps
batch_size: 256

# parallel
device: cuda # cuda
training_num: 20 # 64
test_num: 2 # 8

# Algorithm
alpha: 0.2 # entropy regularization coefficient
auto_alpha: True
alpha_lr: 0.0003 # works if open auto alpha
tau: 0.005
gamma: 0.95

# dir
logdir: log
resume_path: null
save_render: False

# render
watch_train: False # if show demo directly
render: 0.00 # render time rate