# environment
info: use online to train 2 Panda
env: PandaPickAndPlace2-v2
reward_type: sparse
use_her: True
norm_obs: False
seed: 5
curriculum: False
strategy: online

# buffer
use_PER: False
buffer_size: 10000000
replay_k: 4

# network
hidden_sizes: [256, 256]

# train
actor_lr: 1.0e-3
critic_lr: 1.0e-3
start_timesteps: 32000 # warmup
epoch: 100 # save times
step_per_epoch: 640000 # save interval (50repeat)
step_per_collect: 6400 #(64path) after collect #, update
update_per_step: 0.1 # repeat update time
estimation_step: 1 # look ahead time steps
batch_size: 4096

# parallel
device: cuda # cuda
training_num: 64
test_num: 8

# Algorithm
alpha: 0.2 # entropy regularization coefficient
auto_alpha: True
alpha_lr: 0.0003 # works if open auto alpha
tau: 0.005
gamma: 0.95

# dir
logdir: log
resume_path: null
save_render: False

# render
watch_train: False # if show demo directly
render: 0 # render time rate
render_timesteps: 100 # render time rate