# environment
info: (update:collect more data before update) Use SB03 her parameters to train Pick And Place
env: FetchPickAndPlace-v1
seed: 5
use_her: True

# buffer
buffer_size: 1000000
replay_k: 4

# network
hidden_sizes: [512, 512, 512]

# train
actor_lr: 1.0e-3
critic_lr: 1.0e-3
# start_timesteps: 160000 # warmup·
start_timesteps: 10000 # warmup
epoch: 100 # save times
step_per_epoch: 10000 # save interval (50repeat)
step_per_collect: 5000 # 2 #(64path) after collect #, update
update_per_step: 1 # repeat update time
estimation_step: 1 # look ahead time steps
batch_size: 1024

# parallel
device: cuda # cuda
training_num: 50 # 2
test_num: 10

# Algorithm
alpha: 0.2 # entropy regularization coefficient
auto_alpha: True
alpha_lr: 0.0003 # works if open auto alpha
tau: 0.05
gamma: 0.95

# dir
logdir: log
resume_path: null
save_render: False

# render
watch_train: False # if show demo directly
render: 0.00 # render time rate