# environment
info: Online Replay k=4, 3200collect,Use SB her parameters to train Reach
env: FetchReach-v1
dim: 2
reward_type: sparse
use_her: True
norm_obs: True
seed: 5

# buffer
# buffer_size: 16000000
buffer_size: 1000000
replay_k: 4

# network
hidden_sizes: [64, 64]

# train
actor_lr: 1.0e-3
critic_lr: 1.0e-3
start_timesteps: 32000 # warmup
epoch: 10 # save times
step_per_epoch: 320000 # save interval (50repeat)
step_per_collect: 3200 #(64path) after collect #, update
update_per_step: 1 # repeat update time
estimation_step: 1 # look ahead time steps
batch_size: 256

# parallel
device: cuda # cuda
training_num: 64
test_num: 8
s
# Algorithm
alpha: 0.2 # entropy regularization coefficient
auto_alpha: True
alpha_lr: 0.0003 # works if open auto alpha
tau: 0.005
gamma: 0.95

# dir
logdir: log
resume_path: null
save_render: False

# render
watch_train: False # if show demo directly
render: 0.00 # render time rate